<script>
        function autoFillLocation() {

            const locationData = {
                'minglanilla': { province: 'Cebu', country: 'Philippines' },
                'cebu city': { province: 'Cebu', country: 'Philippines' },
                'lapu-lapu city': { province: 'Cebu', country: 'Philippines' },
                'toledo city': { province: 'Cebu', country: 'Philippines' },
                'talisay city': { province: 'Cebu', country: 'Philippines' },
                'carcar city': { province: 'Cebu', country: 'Philippines' },
                'lapu-lapu': { province: 'Cebu', country: 'Philippines' },
                'toledo': { province: 'Cebu', country: 'Philippines' },
                'talisay': { province: 'Cebu', country: 'Philippines' },
                'carcar': { province: 'Cebu', country: 'Philippines' },
                'bantayan': { province: 'Cebu', country: 'Philippines' },
                'samboan': { province: 'Cebu', country: 'Philippines' },
                'moalboal': { province: 'Cebu', country: 'Philippines' },
                'dalaguete': { province: 'Cebu', country: 'Philippines' },
                'sogod': { province: 'Cebu', country: 'Philippines' },
                'argao': { province: 'Cebu', country: 'Philippines' },
                'naga': { province: 'Cebu', country: 'Philippines' }, 
                'naga city': { province: 'Cebu', country: 'Philippines' }, 
                'pilar': { province: 'Cebu', country: 'Philippines' },
                'tabuelan': { province: 'Cebu', country: 'Philippines' },
                'balamban': { province: 'Cebu', country: 'Philippines' },
                'carmen': { province: 'Cebu', country: 'Philippines' },
                'consolacion': { province: 'Cebu', country: 'Philippines' },
                'liloan': { province: 'Cebu', country: 'Philippines' },
                'san fernando': { province: 'Cebu', country: 'Philippines' },
                'santa fe': { province: 'Cebu', country: 'Philippines' },
                'tabogon': { province: 'Cebu', country: 'Philippines' },
                'dumanjug': { province: 'Cebu', country: 'Philippines' },
                'santa catalina': { province: 'Cebu', country: 'Philippines' },
                'aloguinsan': { province: 'Cebu', country: 'Philippines' },
                'bogo city': { province: 'Cebu', country: 'Philippines' },
                'cordova': { province: 'Cebu', country: 'Philippines' },
                'mactan': { province: 'Cebu', country: 'Philippines' },
                'santa rosa': { province: 'Cebu', country: 'Philippines' }, 
                'sogod': { province: 'Cebu', country: 'Philippines' }, 
                'tuburan': { province: 'Cebu', country: 'Philippines' },
                'manila': { province: 'Metro Manila', country: 'Philippines' },
                'quezon city': { province: 'Metro Manila', country: 'Philippines' },
                'makati': { province: 'Metro Manila', country: 'Philippines' },
                'taguig': { province: 'Metro Manila', country: 'Philippines' },
                'pasig': { province: 'Metro Manila', country: 'Philippines' },
                'caloocan': { province: 'Metro Manila', country: 'Philippines' },
                'davao city': { province: 'Davao del Sur', country: 'Philippines' },
                'cebu city': { province: 'Cebu', country: 'Philippines' },
                'iloilo city': { province: 'Iloilo', country: 'Philippines' },
                'bacolod': { province: 'Negros Occidental', country: 'Philippines' },
                'zamboanga city': { province: 'Zamboanga del Sur', country: 'Philippines' },
                'cagayan de oro': { province: 'Misamis Oriental', country: 'Philippines' },
                'general santos': { province: 'South Cotabato', country: 'Philippines' },
                'antipolo': { province: 'Rizal', country: 'Philippines' },
                'san fernando': { province: 'Pampanga', country: 'Philippines' },
                'baguio': { province: 'Benguet', country: 'Philippines' },
                'dagupan': { province: 'Pangasinan', country: 'Philippines' },
                'tarlac city': { province: 'Tarlac', country: 'Philippines' },
                'san pablo': { province: 'Laguna', country: 'Philippines' },
                'batangas city': { province: 'Batangas', country: 'Philippines' },
                'lucena': { province: 'Quezon', country: 'Philippines' },
                'naga city': { province: 'Camarines Sur', country: 'Philippines' },
                'legazpi': { province: 'Albay', country: 'Philippines' },
                'sorsogon city': { province: 'Sorsogon', country: 'Philippines' },
                'tacloban': { province: 'Leyte', country: 'Philippines' },
                'orlando': { province: 'Eastern Samar', country: 'Philippines' },
                'rodriguez': { province: 'Rizal', country: 'Philippines' },
                'marikina': { province: 'Metro Manila', country: 'Philippines' },
                'muntinlupa': { province: 'Metro Manila', country: 'Philippines' },
                'paranaque': { province: 'Metro Manila', country: 'Philippines' },
                'pasay': { province: 'Metro Manila', country: 'Philippines' },
                'bataan': { province: 'Bataan', country: 'Philippines' },
                'bulacan': { province: 'Bulacan', country: 'Philippines' },
                'pampanga': { province: 'Pampanga', country: 'Philippines' },
                'tarlac': { province: 'Tarlac', country: 'Philippines' },
                'ilocos norte': { province: 'Ilocos Norte', country: 'Philippines' },
                'ilocos sur': { province: 'Ilocos Sur', country: 'Philippines' },
                'la union': { province: 'La Union', country: 'Philippines' },
                'pangasinan': { province: 'Pangasinan', country: 'Philippines' },
                'batanes': { province: 'Batanes', country: 'Philippines' },
                'apayao': { province: 'Apayao', country: 'Philippines' },
                'kalinga': { province: 'Kalinga', country: 'Philippines' },
                'mount province': { province: 'Mountain Province', country: 'Philippines' },
                'ifugao': { province: 'Ifugao', country: 'Philippines' },
                'nueva vizcaya': { province: 'Nueva Vizcaya', country: 'Philippines' },
                'quirino': { province: 'Quirino', country: 'Philippines' },
                'aurora': { province: 'Aurora', country: 'Philippines' },
                'zambales': { province: 'Zambales', country: 'Philippines' },
                'cavite': { province: 'Cavite', country: 'Philippines' },
                'laguna': { province: 'Laguna', country: 'Philippines' },
                'batangas': { province: 'Batangas', country: 'Philippines' },
                'quezon': { province: 'Quezon', country: 'Philippines' },
                'marinduque': { province: 'Marinduque', country: 'Philippines' },
                'romblon': { province: 'Romblon', country: 'Philippines' },
                'masbate': { province: 'Masbate', country: 'Philippines' },
                'albay': { province: 'Albay', country: 'Philippines' },
                'sorsogon': { province: 'Sorsogon', country: 'Philippines' },
                'leyte': { province: 'Leyte', country: 'Philippines' },
                'biliran': { province: 'Biliran', country: 'Philippines' },
                'samar': { province: 'Samar', country: 'Philippines' },
                'eastern samar': { province: 'Eastern Samar', country: 'Philippines' },
                'northern samar': { province: 'Northern Samar', country: 'Philippines' },
                'western samar': { province: 'Western Samar', country: 'Philippines' },
                'negros oriental': { province: 'Negros Oriental', country: 'Philippines' },
                'negros occidental': { province: 'Negros Occidental', country: 'Philippines' },
                'cebu': { province: 'Cebu', country: 'Philippines' },
                'bohol': { province: 'Bohol', country: 'Philippines' },
                'siquijor': { province: 'Siquijor', country: 'Philippines' },
                'davao del norte': { province: 'Davao del Norte', country: 'Philippines' },
                'davao de oro': { province: 'Davao de Oro', country: 'Philippines' },
                'davao del sur': { province: 'Davao del Sur', country: 'Philippines' },
                'south cotabato': { province: 'South Cotabato', country: 'Philippines' },
                'sultan kudarat': { province: 'Sultan Kudarat', country: 'Philippines' },
                'cotabato': { province: 'Cotabato', country: 'Philippines' },
                'zamboanga del norte': { province: 'Zamboanga del Norte', country: 'Philippines' },
                'zamboanga del sur': { province: 'Zamboanga del Sur', country: 'Philippines' },
                'zamboanga sibugay': { province: 'Zamboanga Sibugay', country: 'Philippines' },
                'misamis oriental': { province: 'Misamis Oriental', country: 'Philippines' },
                'misamis occidental': { province: 'Misamis Occidental', country: 'Philippines' },
                'lanao del norte': { province: 'Lanao del Norte', country: 'Philippines' },
                'lanao del sur': { province: 'Lanao del Sur', country: 'Philippines' },
                'bukidnon': { province: 'Bukidnon', country: 'Philippines' },
                'agusan del norte': { province: 'Agusan del Norte', country: 'Philippines' },
                'agusan del sur': { province: 'Agusan del Sur', country: 'Philippines' },
                'surigao del norte': { province: 'Surigao del Norte', country: 'Philippines' },
                'surigao del sur': { province: 'Surigao del Sur', country: 'Philippines' },
                'butuan': { province: 'Agusan del Norte', country: 'Philippines' },
                'caraga': { province: 'Caraga', country: 'Philippines' },
                'ncr': { province: 'National Capital Region', country: 'Philippines' },
                'tokyo': { province: 'Tokyo Metropolis', country: 'Japan' },
                'osaka': { province: 'Osaka Prefecture', country: 'Japan' },
                'new york': { province: 'New York', country: 'United States' },
                'los angeles': { province: 'California', country: 'United States' },
                'london': { province: 'Greater London', country: 'United Kingdom' },
                'paris': { province: 'Île-de-France', country: 'France' },
                'berlin': { province: 'Berlin', country: 'Germany' },
                'sydney': { province: 'New South Wales', country: 'Australia' },
                'toronto': { province: 'Ontario', country: 'Canada' },
                'vancouver': { province: 'British Columbia', country: 'Canada' },
                'mumbai': { province: 'Maharashtra', country: 'India' },
                'delhi': { province: 'Delhi', country: 'India' },
                'beijing': { province: 'Beijing', country: 'China' },
                'shanghai': { province: 'Shanghai', country: 'China' },
                'cairo': { province: 'Cairo', country: 'Egypt' },
                'nairobi': { province: 'Nairobi', country: 'Kenya' },
                'moscow': { province: 'Moscow', country: 'Russia' },
                'sao paulo': { province: 'São Paulo', country: 'Brazil' },
                'buenos aires': { province: 'Buenos Aires', country: 'Argentina' },
                'seoul': { province: 'Seoul', country: 'South Korea' },
                'bangkok': { province: 'Bangkok', country: 'Thailand' },
                'jakarta': { province: 'Jakarta', country: 'Indonesia' },
                'mexico city': { province: 'Mexico City', country: 'Mexico' },
                'rome': { province: 'Lazio', country: 'Italy' },
                'madrid': { province: 'Madrid', country: 'Spain' },
                'lisbon': { province: 'Lisbon', country: 'Portugal' },
                'stockholm': { province: 'Stockholm', country: 'Sweden' },
                'oslo': { province: 'Oslo', country: 'Norway' },
                'copenhagen': { province: 'Capital Region', country: 'Denmark' },
                'helsinki': { province: 'Uusimaa', country: 'Finland' },
                'dublin': { province: 'Leinster', country: 'Ireland' },
                'athens': { province: 'Attica', country: 'Greece' },
                'kuala lumpur': { province: 'Federal Territory', country: 'Malaysia' },
                'manama': { province: 'Capital Governorate', country: 'Bahrain' },
                'doha': { province: 'Doha', country: 'Qatar' },
                'abu dhabi': { province: 'Abu Dhabi', country: 'United Arab Emirates' },
                'riyadh': { province: 'Riyadh', country: 'Saudi Arabia' },
                'baghdad': { province: 'Baghdad', country: 'Iraq' },
                'tehran': { province: 'Tehran', country: 'Iran' },
                'islamabad': { province: 'Islamabad', country: 'Pakistan' },
                'lahore': { province: 'Punjab', country: 'Pakistan' },
                'karachi': { province: 'Sindh', country: 'Pakistan' },
                'hanoi': { province: 'Hanoi', country: 'Vietnam' },
                'singapore': { province: 'Central Region', country: 'Singapore' },
                'auckland': { province: 'Auckland', country: 'New Zealand' },
                'wellington': { province: 'Wellington', country: 'New Zealand' },
                'cape town': { province: 'Western Cape', country: 'South Africa' },
                'johannesburg': { province: 'Gauteng', country: 'South Africa' },
                'accra': { province: 'Greater Accra', country: 'Ghana' },
                'lagos': { province: 'Lagos', country: 'Nigeria' },
                'kigali': { province: 'Kigali', country: 'Rwanda' },
                'lima': { province: 'Lima', country: 'Peru' },
                'caracas': { province: 'Caracas', country: 'Venezuela' },
                'santiago': { province: 'Santiago Metropolitan', country: 'Chile' },
                'bogota': { province: 'Bogotá', country: 'Colombia' },
                'quito': { province: 'Pichincha', country: 'Ecuador' },
                'asuncion': { province: 'Asunción', country: 'Paraguay' },
                'montevideo': { province: 'Montevideo', country: 'Uruguay' },
                'san salvador': { province: 'San Salvador', country: 'El Salvador' },
                'managua': { province: 'Managua', country: 'Nicaragua' },
                'tunis': { province: 'Tunis', country: 'Tunisia' },
                'algiers': { province: 'Algiers', country: 'Algeria' },
                'casablanca': { province: 'Casablanca-Settat', country: 'Morocco' },
                'addis ababa': { province: 'Addis Ababa', country: 'Ethiopia' },
                'lilongwe': { province: 'Lilongwe', country: 'Malawi' },
                'harare': { province: 'Harare', country: 'Zimbabwe' },
                'kabul': { province: 'Kabul', country: 'Afghanistan' },
                'dhaka': { province: 'Dhaka', country: 'Bangladesh' },
                'colombo': { province: 'Western', country: 'Sri Lanka' },
                'male': { province: 'Malé', country: 'Maldives' },
                'tbilisi': { province: 'Tbilisi', country: 'Georgia' },
                'yerevan': { province: 'Yerevan', country: 'Armenia' },
                'baku': { province: 'Baku', country: 'Azerbaijan' },
                'astana': { province: 'Nur-Sultan', country: 'Kazakhstan' },
                'bishkek': { province: 'Bishkek', country: 'Kyrgyzstan' },
                'tashkent': { province: 'Tashkent', country: 'Uzbekistan' },
                'ashgabat': { province: 'Ashgabat', country: 'Turkmenistan' },
                'dushanbe': { province: 'Dushanbe', country: 'Tajikistan' },
                'nursultan': { province: 'Akmola Region', country: 'Kazakhstan' },
                'sana': { province: 'Sana\'a', country: 'Yemen' },
                'muscat': { province: 'Muscat', country: 'Oman' }
            };

        // Function to handle input for both city and home_city
        function handleCityInput(cityInput, provinceInput, countrySelect) {
            cityInput.addEventListener('input', function() {
                const city = cityInput.value.toLowerCase().trim();
                if (locationData[city]) {
                    provinceInput.value = locationData[city].province;
                    countrySelect.value = locationData[city].country;
                } else {
                    provinceInput.value = ''; 
                    countrySelect.value = ''; 
                }
            });
        }

        // Get the input elements for city and home_city
        const cityInput = document.querySelector('input[name="city"]');
        const provinceInput = document.querySelector('input[name="province"]');
        const countrySelect = document.querySelector('select[name="country"]');

        const homeCityInput = document.querySelector('input[name="home_city"]');
        const homeProvinceInput = document.querySelector('input[name="home_province"]');
        const homeCountrySelect = document.querySelector('select[name="home_country"]');

        // Attach event listeners for both sets of inputs
        if (cityInput) {
            handleCityInput(cityInput, provinceInput, countrySelect);
        }
        if (homeCityInput) {
            handleCityInput(homeCityInput, homeProvinceInput, homeCountrySelect);
        }
    }

    document.addEventListener('DOMContentLoaded', autoFillLocation);
</script>